import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Home from "./page";
import Footer from "@/components/layout/footer";
import CategoryList from "./category/page";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Header />
          {/* <CategoryList/> */}
          <div style={{ minHeight: "calc(100vh - 84px)" }} >
            {children}
          </div>
          <Footer/>
      </body>
    </html>
  );
}
