import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'react-loading-skeleton/dist/skeleton.css'
import Footer from "@/components/layout/footer";
import Rootheader from "@/components/layout/rootheader";
import { Provider } from 'react-redux';
import { store } from "@/redux/store";
import ReduxProvider from "@/components/provider";


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: {
    // absolute:'',
    default:'Airbnb Travel&Tour',//default can set title then it shuld take this default title
    template:'%s | airbnb'//if we use in page only title tne it should allow or we use title-absolute then it should be ignored
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <Rootheader />
          <div style={{ minHeight: "calc(100vh)" }} className=" pt-[68px] md:pt-[70px] bg-primary pb-[50px] md:pb-[55px]" >
       
            {children}
       
          </div>
          <Footer/>
        </ReduxProvider>
          
      </body>
    </html>
  );
}
