import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/components/layout/footer";


const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
  icons: {
    icon: "../assets/images/logo/airbnb-logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Header />
          <div style={{ minHeight: "calc(100vh)" }} className=" pt-[58px] md:pt-[70px] bg-primary " >
            {children}
          </div>
          <Footer/>
      </body>
    </html>
  );
}
